In [1]:
import pandas as pd

In [20]:
air_1_df = pd.read_csv("../data/2016_1.csv", encoding='EUC-KR')
air_2_df = pd.read_csv("../data/2016_2.csv", encoding='EUC-KR')
air_3_df = pd.read_csv("../data/2016_3.csv", encoding='EUC-KR')
air_4_df = pd.read_csv("../data/2016_4.csv", encoding='EUC-KR')

In [26]:
air_df = pd.concat([air_1_df, air_2_df, air_3_df, air_4_df])

In [49]:
air_df.columns

Index(['지역', '측정소코드', '측정소명', '측정일시', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25',
       '주소'],
      dtype='object')

In [38]:
from collections import Counter
Counter(air_df['지역'])

Counter({'강원 강릉시': 8784,
         '강원 고성군': 8784,
         '강원 동해시': 8784,
         '강원 삼척시': 8784,
         '강원 양구군': 8784,
         '강원 원주시': 17568,
         '강원 정선군': 8784,
         '강원 춘천시': 17568,
         '강원 횡성군': 8784,
         '경기 가평군': 8784,
         '경기 고양시': 28560,
         '경기 과천시': 17568,
         '경기 광명시': 17568,
         '경기 광주시': 8784,
         '경기 구리시': 17568,
         '경기 군포시': 17568,
         '경기 김포시': 26352,
         '경기 남양주시': 17568,
         '경기 동두천시': 8784,
         '경기 부천시': 43920,
         '경기 성남시': 70272,
         '경기 수원시': 61488,
         '경기 시흥시': 26352,
         '경기 안산시': 70272,
         '경기 안성시': 8784,
         '경기 안양시': 35136,
         '경기 양주시': 8784,
         '경기 양평군': 8784,
         '경기 여주시': 8784,
         '경기 연천군': 8784,
         '경기 오산시': 8784,
         '경기 용인시': 35136,
         '경기 의왕시': 17568,
         '경기 의정부시': 17568,
         '경기 이천시': 17568,
         '경기 파주시': 17568,
         '경기 평택시': 26352,
         '경기 포천시': 17568,
         '경기 하남시': 8784,
         '경기 화성시': 26352,
         '경남 거제시': 17568,
         '경남 거창군': 8784,
         '경남 김해시': 26352,
         '경남 사천시': 8784,
         '경남 양산시': 17568,
         '경남 진주시': 26352,
         '경남 창원시': 87840,
         '경남 하동군': 8784,
         '경북 경산시': 8784,
         '경북 경주시': 8784,
         '경북 구미시': 35136,
         '경북 김천시': 8784,
         '경북 안동시': 8784,
         '경북 영덕군': 8784,
         '경북 영주시': 8784,
         '경북 영천시': 8784,
         '경북 울릉군': 8784,
         '경북 의성군': 8784,
         '경북 포항시': 43920,
         '광주 광산구': 17568,
         '광주 남구': 8784,
         '광주 동구': 8784,
         '광주 북구': 26352,
         '광주 서구': 17568,
         '대구 남구': 8784,
         '대구 달서구': 9528,
         '대구 달성군': 8784,
         '대구 동구': 17568,
         '대구 북구': 17568,
         '대구 서구': 17568,
         '대구 수성구': 17568,
         '대구 중구': 8784,
         '대전 대덕구': 17568,
         '대전 동구': 8784,
         '대전 서구': 26352,
         '대전 유성구': 17568,
         '대전 중구': 17568,
         '부산 강서구': 17568,
         '부산 금정구': 17568,
         '부산 기장군': 17568,
         '부산 남구': 8784,
         '부산 동구': 17568,
         '부산 동래구': 17568,
         '부산 부산진구': 8784,
         '부산 북구': 8784,
         '부산 사상구': 8784,
         '부산 사하구': 8784,
         '부산 서구': 8784,
         '부산 수영구': 8784,
         '부산 연제구': 8784,
         '부산 영도구': 8784,
         '부산 중구': 8784,
         '부산 해운대구': 8784,
         '서울': 342576,
         '세종': 17568,
         '울산 남구': 61488,
         '울산 동구': 8784,
         '울산 북구': 17568,
         '울산 울주군': 35136,
         '울산 중구': 8784,
         '인천 강화군': 17568,
         '인천 계양구': 8784,
         '인천 남구': 17568,
         '인천 남동구': 26352,
         '인천 동구': 17568,
         '인천 부평구': 17568,
         '인천 서구': 35136,
         '인천 연수구': 8784,
         '인천 옹진군': 17568,
         '인천 중구': 17568,
         '전남 광양시': 35136,
         '전남 목포시': 17568,
         '전남 순천시': 35136,
         '전남 여수시': 43920,
         '전남 영암군': 8784,
         '전남 화순군': 8784,
         '전북 고창군': 8784,
         '전북 군산시': 26352,
         '전북 김제시': 8784,
         '전북 남원시': 8784,
         '전북 부안군': 8784,
         '전북 익산시': 26352,
         '전북 임실군': 8784,
         '전북 전주시': 35136,
         '전북 정읍시': 8784,
         '제주 서귀포시': 8784,
         '제주 제주시': 26352,
         '충남 공주시': 8784,
         '충남 당진군': 17568,
         '충남 서산시': 17568,
         '충남 아산시': 8784,
         '충남 천안시': 26352,
         '충남 태안군': 8784,
         '충북 괴산군': 8784,
         '충북 단양군': 8784,
         '충북 제천시': 8784,
         '충북 청주시': 52704,
         '충북 충주시': 17568,
         '충북 진천군': 5136})

In [82]:
interested_places = {'BS': '부산',
         'CB': '충북',
         'CN': '충남',
         'DG': '대구',
         'DJ': '대전',
         'GB': '경북',
         'GG': '경기',
         'GJ': '광주',
         'GN': '경남',
         'GW': '강원',
         'IC': '인천',
         'JB': '전북',
         'JJ': '제주',
         'JN': '전남',
         'SU': '서울',
         'US': '울산'}

In [83]:
import datetime
def my_to_datetime(date_str):
    date_str = str(date_str)
    if date_str[8:10] != '24':
        return pd.to_datetime(date_str, format='%Y%m%d%H').date()

    date_str = date_str[0:8] + '00' + date_str[10:]
    return pd.to_datetime(date_str, format='%Y%m%d%H').date() + \
           datetime.timedelta(days=1)

In [84]:
date_air_df = pd.DataFrame()

In [87]:
for place, name in interested_places.items():
    place_air_df = air_df[air_df['지역'].str[:2] == name]
    place_air_df['date'] = [my_to_datetime(d) for d in place_air_df['측정일시']]
    place_air_df1 = place_air_df.groupby('date').agg(
        SO2 = pd.NamedAgg(column="SO2", aggfunc='mean'), 
        CO = pd.NamedAgg(column="CO", aggfunc='mean'),
        O3 = pd.NamedAgg(column="O3", aggfunc='mean'),
        NO2 = pd.NamedAgg(column="NO2", aggfunc='mean'),
        PM10 = pd.NamedAgg(column="PM10", aggfunc='mean'),
        PM25 = pd.NamedAgg(column='PM25',aggfunc='mean')
    )
    place_air_df1['place'] = place
    date_air_df = pd.concat([date_air_df, place_air_df1])

/Users/jaemincheun/anaconda3/envs/parkinson/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [91]:
len(Counter(date_air_df['place']))

16

In [89]:
date_air_df

                 SO2        CO        O3       NO2       PM10       PM25 place
date
2016-01-01  0.006525  0.557214  0.019673  0.024590  55.336170  45.972281    BS
2016-01-02  0.007905  0.671599  0.018108  0.030591  58.845214  46.401222    BS
2016-01-03  0.008123  0.755093  0.014266  0.034563  61.206413  47.030242    BS
2016-01-04  0.006948  0.666114  0.022026  0.033419  81.784394  63.100616    BS
2016-01-05  0.005035  0.475176  0.014104  0.031602  46.255187  30.691383    BS
...              ...       ...       ...       ...        ...        ...   ...
2016-12-28  0.004378  0.526462  0.015586  0.025425  32.575419  17.271429    US
2016-12-29  0.003717  0.511944  0.021564  0.021303  29.325000  15.546154    US
2016-12-30  0.003744  0.454444  0.018025  0.024092  26.633053  10.904000    US
2016-12-31  0.003542  0.596944  0.023733  0.019958  34.423398  22.215278    US
2017-01-01  0.003333  0.613333  0.012933  0.030267  40.666667  35.166667    US

[5872 rows x 7 columns]

In [92]:
date_air_df.reset_index(level=0, inplace=True)

In [93]:
date_air_df[pd.to_datetime(date_air_df['date'], format='%Y-%m-%d').dt.year == 2016]

,index,date,SO2,CO,O3,NO2,PM10,PM25,place
0,0,2016-01-01,0.006525,0.557214,0.019673,0.024590,55.336170,45.972281,BS
1,1,2016-01-02,0.007905,0.671599,0.018108,0.030591,58.845214,46.401222,BS
2,2,2016-01-03,0.008123,0.755093,0.014266,0.034563,61.206413,47.030242,BS
3,3,2016-01-04,0.006948,0.666114,0.022026,0.033419,81.784394,63.100616,BS
4,4,2016-01-05,0.005035,0.475176,0.014104,0.031602,46.255187,30.691383,BS
...,...,...,...,...,...,...,...,...,...
5866,5866,2016-12-27,0.003358,0.537222,0.023878,0.016692,25.876056,17.105634,US
5867,5867,2016-12-28,0.004378,0.526462,0.015586,0.025425,32.575419,17.271429,US
5868,5868,2016-12-29,0.003717,0.511944,0.021564,0.021303,29.325000,15.546154,US
5869,5869,2016-12-30,0.003744,0.454444,0.018025,0.024092,26.633053,10.904000,US
5870,5870,2016-12-31,0.003542,0.596944,0.023733,0.019958,34.423398,22.215278,US

In [94]:
del date_air_df['index']

In [95]:
Counter(date_air_df['place'
])

Counter({'BS': 367,
         'CB': 367,
         'CN': 367,
         'DG': 367,
         'DJ': 367,
         'GB': 367,
         'GG': 367,
         'GJ': 367,
         'GN': 367,
         'GW': 367,
         'IC': 367,
         'JB': 367,
         'JJ': 367,
         'JN': 367,
         'SU': 367,
         'US': 367})

In [96]:
date_air_df.to_csv('../data/air_quality_city.csv', index=False)